server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_empty
    parser:
      strict-duplicate-detection: true
app:
  executor:
    initialDelay: 1
    delay: 1
    queueCapacity: 50
    workshopScheduled:
      corePoolSize: 1
      maxPoolSize: 1
      queueCapacity: 50
    repairingServiceScheduled:
      corePoolSize: 1
      maxPoolSize: 2
      queueCapacity: 50
    repairingService:
      corePoolSize: 4
      maxPoolSize: 5
      queueCapacity: 50
      keepAliveTime: 5
  time-to-fix:
    byType:
      artificial: 1
      human: 2
    byComponent:
      consciousness: 10_000
      emotionChip: 5_000
      memoryModule: 7_000
  time-to-create:
    byType:
      artificial: 1
      human: 2
    byComponent:
      consciousness: 15_000
      emotionChip: 8_000
      memoryModule: 11_000
  success-rate:
    byType:
      artificial: 95
      human: 80
    byComponent:
      consciousness: 80
      emotionChip: 85
      memoryModule: 95