server:
  port: 8080
logging:
  level:
    ru:
      mai: TRACE
spring:
  jackson:
    default-property-inclusion: non_empty
    parser:
      strict-duplicate-detection: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    hikari:
      schema: duties
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
app:
  executor:
    initialDelay: 1
    delay: 1
    queueCapacity: 50
    workshop:
      corePoolSize: 1
      maxPoolSize: 1
  time-to-fix:
    byType:
      artificial: 10
      human: 20
    byComponent:
      consciousness: 10
      emotionChip: 5
      memoryModule: 7
  success-rate:
    byType:
      artificial: 95
      human: 40
    byComponent:
      consciousness: 80
      emotionChip: 85
      memoryModule: 95