spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    hikari:
      schema: duties
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}

#  flyway:
#    enabled: true
#    validate-on-migrate: true