server:
  port: 8080
logging:
  level:
    ru:
      mai: TRACE
spring:
  jackson:
    default-property-inclusion: non_empty
    parser:
      strict-duplicate-detection: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    hikari:
      schema: duties
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
app:
  executor:
    initialDelay: 1
    delay: 1
    queueCapacity: 50
    workshopScheduled:
      corePoolSize: 1
      maxPoolSize: 1
      queueCapacity: 50
    repairingServiceScheduled:
      corePoolSize: 1
      maxPoolSize: 2
      queueCapacity: 50
    repairingService:
      corePoolSize: 1
      maxPoolSize: 2
      queueCapacity: 50
      keepAliveTime: 5
  time-to-fix:
    byType:
      artificial: 10
      human: 20
    byComponent:
      consciousness: 10
      emotionChip: 5
      memoryModule: 7
  time-to-create:
    byType:
      artificial: 1
      human: 2
    byComponent:
      consciousness: 20
      emotionChip: 10
      memoryModule: 14
  success-rate:
    byType:
      artificial: 95
      human: 40
    byComponent:
      consciousness: 80
      emotionChip: 85
      memoryModule: 95